export type TProducts = {
    id: number
    nome: string
    descricao: string
    garantia: number
    preco: number
    image_1?: string
    image_2?: string
    image_3?: string
}

export const products = [
    {
        "id": 1,
        "nome": "Placa Mãe MSI A520M-A PRO, AMD AM4, mATX, DDR4",
        "descricao": "Placa-Mãe MSI A520M-A da série PRO ajuda os usuários a trabalhar de forma mais inteligente, oferecendo uma experiência única em eficiência e produtividade para usuários DIY. Seu funcionamento estável e montagem de alta qualidade, fazem com que a Placa-Mãe MSI A520M-A PRO ofereça muito mais que fluxos de trabalho profissionais otimizados: são menos problemas para o usuário e máxima longevidade.",
        "garantia": 36,
        "preco": 500,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/280890/placa-mae-msi-a520m-a-pro-amd-am4-matx-ddr4_1646852577_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/280890/placa-mae-msi-a520m-a-pro-amd-am4-matx-ddr4_1646852578_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/280890/placa-mae-msi-a520m-a-pro-amd-am4-matx-ddr4_1646852579_gg.jpg",
    },
    {
        "id": 2,
        "nome": "Placa Mãe ASRock B450M Steel Legend, AMD AM4, mATX, DDR4",
        "descricao": "Placa-mãe ASRock B450M Steel Legend AMD DDR4 Resistente como aço, verdadeira lenda a Steel Legend representa o estado filosófico da sólida durabilidade e irresistível estética. Construída ao redor das especificações e recursos mais exigentes, a série Steel Legend visa os usuários do dia a dia e entusiastas mainstream!Oferecendo uma forte gama de materiais/componentes para assegurar um desempenho estável e confiável.",
        "garantia": 12,
        "preco": 450,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/100672/placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_1552586908_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/100672/placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_1552586917_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/100672/placa-mae-asrock-b450m-steel-legend-amd-am4-matx-ddr4-90-mxb9y0-a0uayz_1552586907_gg.jpg",
    },
    {
        "id": 3,
        "nome": "Placa Mãe Gigabyte Aorus B450 Elite V2, AMD B450, ATX, DDR4, (rev. 1.0)",
        "descricao": "Placa-mãe AMD B450 AORUS com 8 + 2 fases Digital Team Power Design, Dual M.2 com One Thermal Guard, GIGABYTE Gaming LAN com Bandwidth Management, RGB FUSION 2.0, CEC 2019 Ready.",
        "garantia": 12,
        "preco": 550,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/127868/placa-mae-gigabyte-aorus-b450-elite-v2-amd-b450-atx-ddr4-rev-1-0-_1599763669_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/127868/placa-mae-gigabyte-aorus-b450-elite-v2-amd-b450-atx-ddr4-rev-1-0-_1599763670_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/127868/placa-mae-gigabyte-aorus-b450-elite-v2-amd-b450-atx-ddr4-rev-1-0-_1599763668_gg.jpg",
    },
    {
        "id": 4,
        "nome": "Placa Mae Asus TUF Gaming X670E-Plus, AMD X670, AM5, DDR5 - 90MB1BJ0-C1BAY0",
        "descricao": "Placa-Mãe Asus TUF Gaming X670E-Plus, AMD X670, AM5, DDR5. As placas-mãe TUF GAMING também passam por rigorosos audios de resistência para garantir que possam lidar com condições em que outras podem falhar. Esteticamente, este modelo incorpora elementos de design geométrico e off-black robustos para refletir a confiabilidade e estabilidade que definem a série TUF GAMING. Com fornecimento de energia atualizado e opções abrangentes de refrigeração para alimentar as CPUs mais recentes da AMD, além de suporte para memória e armazenamento mais rápidos, o TUF GAMING X670E-PLUS é a base perfeita para o seu próximo equipamento de batalha AMD de alta contagem de núcleos.",
        "garantia": 12,
        "preco": 700,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/404209/Placa-M-e-Asus-TUF-Gaming-X670E-Plus-AMD-X670-AM5-ATX-DDR5-90MB1BJ0-M0EAY0_1713209296_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/404209/Placa-M-e-Asus-TUF-Gaming-X670E-Plus-AMD-X670-AM5-ATX-DDR5-90MB1BJ0-M0EAY0_1713209307_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/404209/Placa-M-e-Asus-TUF-Gaming-X670E-Plus-AMD-X670-AM5-ATX-DDR5-90MB1BJ0-M0EAY0_1713209331_gg.jpg",
    },
    {
        "id": 5,
        "nome": "Placa de Vídeo RTX 4060 VENTUS 2x Black OC MSI NVIDIA GeForce, 8GB GDDR6, DLSS, Ray Tracing",
        "descricao": "Placa de Vídeo MSI NVIDIA GeForce RTX 4060 VENTUS 2X Black 8G OC. O VENTUS traz uma experiência fundamentalmente sólida para usuários que procuram uma placa gráfica de alto desempenho. Um design atualizado de aparência nítida com o TORX FAN 4.0 permite que o VENTUS passe por qualquer tarefa. O TORX FAN 4.0 é construído com base no trabalho em equipe, com pares de pás do ventilador unidas por um design de anel externo vinculado que concentra o fluxo de ar no sistema de resfriamento Dual-Fan.",
        "garantia": 12,
        "preco": 2500,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/461395/placa-de-video-rtx-4060-ti-ventus-msi-nvidia-geforce-8-gb-gddr6-dlss-ray-tracing_1684770175_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/461395/placa-de-video-rtx-4060-ti-ventus-msi-nvidia-geforce-8-gb-gddr6-dlss-ray-tracing_1684770170_gg.jpg",
    },
    {
        "id": 6,
        "nome": "Placa de Vídeo RTX 4060 AERO OC Gigabyte NVIDIA GeForce, 8GB GDDR6, RGB, DLSS, Ray Tracing, Branco - GV-N4060AERO OC-8GD",
        "descricao": "Sistema de Refrigeração WINDFORCE com três ventiladores de lâmina exclusivos de 80 mm, tubos de calor de cobre compostos giratórios alternativos que tocam diretamente a GPU, ventiladores ativos 3D e resfriamento de tela. Módulo Térmico Otimizado com tubo de calor de cobre puro que faz contato direto com a GPU para facilitar a transferência de calor aprimorada para o dissipador de calor, otimizando a eficiência de resfriamento da placa gráfica.",
        "garantia": 36,
        "preco": 2700,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/470985/placa-de-video-rtx-4060-aero-oc-gigabyte-nvidia-geforce-8gb-gddr6-rgb-dlss-ray-tracing-branco-gv-n4060aero-oc-8gd_1688049511_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/470985/placa-de-video-rtx-4060-aero-oc-gigabyte-nvidia-geforce-8gb-gddr6-rgb-dlss-ray-tracing-branco-9vn4060ao-00-10_1687970377_gg.jpg",
    },
    {
        "id": 7,
        "nome": "Placa de Vídeo RTX 4090 Asus NVIDIA ROG Strix, 24 GB GDDR6X, ARGB, DLSS, Ray Tracing - ROG-STRIX-RTX4090-O24G-GAMING",
        "descricao": "ROG Strix GeForce RTX 4090 OC Edition 24 GB GDDR6X Multiprocessadores de streaming NVIDIA Ada Lovelace: Desempenho e eficiência de energia até 2x, Núcleos tensores de 4ª geração: desempenho de IA até 2X, Núcleos RT de 3ª Geração: Desempenho de rastreamento de raios até 2X, Ventiladores de tecnologia axial ampliados para 23% mais fluxo de ar.",
        "garantia": 12,
        "preco": 134999,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/387449/placa-de-video-asus-nvidia-rog-strix-rtx-4090-edition-24-gb-gddr6x-argb-dlss-ray-tracing-90yv0iw0-m0nan00_1665170163_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/387449/placa-de-video-asus-nvidia-rog-strix-rtx-4090-edition-24-gb-gddr6x-argb-dlss-ray-tracing-90yv0iw0-m0nan00_1665170154_gg.jpg",
    },
    {
        "id": 8,
        "nome": "Placa de Vídeo GTX 1650 D6 Ventus XS OCV3 MSI NVIDIA GeForce, 4GB GDDR6, G- Sync - 912-V812-003",
        "descricao": "Placa de Vídeo GTX 1650 D6 VENTUS XS. Com um novo design de ventilador duplo, o VENTUS exibe orgulhosamente suas formas industriais em cores neutras para se adequar a qualquer construção.",
        "garantia": 24,
        "preco": 839.99,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/538895/placa-de-video-gtx-1650-d6-ventus-xs-ocv3-msi-nvidia-geforce-4gb-gddr6-912-v812-003_1711386727_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/538895/placa-de-video-gtx-1650-d6-ventus-xs-ocv3-msi-nvidia-geforce-4gb-gddr6-912-v812-003_1711386723_gg.jpg ",
        "image_3": "https://images.kabum.com.br/produtos/fotos/538895/placa-de-video-gtx-1650-d6-ventus-xs-ocv3-msi-nvidia-geforce-4gb-gddr6-912-v812-003_1711386724_gg.jpg",
    },
    {
        "id": 9,
        "nome": "Memória Kingston Fury Beast, 8GB, 3200MHz, DDR4, CL16, Preto - KF432C16BB/8",
        "descricao": "Memória Kingston Fury Beast A memória Kingston FURY Beast DDR4 proporciona um poderoso aumento de performance para jogos, edição de vídeo e renderização.",
        "garantia": 12,
        "preco": 160,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270523_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270526_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/172365/memoria-kingston-fury-beast-8gb-3200mhz-ddr4-cl16-preto-kf432c16bb-8_1626270524_gg.jpg",
    },
    {
        "id": 10,
        "nome": "Memoria Para Notebook Rise Mode Value, 16GB, 3200MHZ, DDR4, CL16 - RM-D4-16G-3200VN",
        "descricao": "Memoria Gamer Rise Mode Value, 16GB. Capacidade de 16GB: Ideal para rodar jogos pesados e executar multitarefas sem problemas.",
        "garantia": 12,
        "preco": 239.99,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/480402/memoria-gamer-rise-mode-value-16gb-3200mhz-ddr4-cl16-para-notebook-rm-d4-16g-3200vn_1703002526_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/480402/memoria-gamer-rise-mode-value-16gb-3200mhz-ddr4-cl16-para-notebook-rm-d4-16g-3200vn_1703002527_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/480402/memoria-gamer-rise-mode-value-16gb-3200mhz-ddr4-cl16-para-notebook-rm-d4-16g-3200vn_1703002525_gg.jpg",
    },
    {
        "id": 11,
        "nome": "Fonte MSI MAG A650BN, 650W, 80 Plus Bronze, PFC Ativo, com cabo, Preto - 306-7ZP2B22-CE0",
        "descricao": "Fonte MSI MAG A650BN. Oferece aos jogadores uma opção de fonte de alimentação de nível básico segura, confiável e eficiente.",
        "garantia": 60,
        "preco": 279.99,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/369658/fonte-msi-mag-a650bn-atx-650w-80-plus-bronze-pfc-ativo-entrada-bivolt-preto-306-7zp2b22-ce0_1665770996_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/369658/fonte-msi-mag-a650bn-atx-650w-80-plus-bronze-pfc-ativo-entrada-bivolt-preto-306-7zp2b22-ce0_1667590559_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/369658/fonte-msi-mag-a650bn-atx-650w-80-plus-bronze-pfc-ativo-entrada-bivolt-preto-306-7zp2b22-ce0_1665770994_gg.jpg",
    },
    {
        "id": 12,
        "nome": "Water Cooler Rise Mode, ARGB, 240mm, AMD/Intel, Preto - RM-WCB-04-ARGB",
        "descricao": "Water Cooler Gamer Rise Mode, ARGB. A escolha perfeita para entusiastas em jogos que desejam manter seus PCs resfriados enquanto exibem um show de leds.",
        "garantia": 12,
        "preco": 179.99,
        "categoria": "hardware",
        "image_1": "https://images.kabum.com.br/produtos/fotos/248205/water-cooler-gamer-rise-mode-argb-intel-e-amd-240mm-preto-rm-wcb-04-argb_1663778106_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/248205/water-cooler-gamer-rise-mode-argb-intel-e-amd-240mm-preto-rm-wcb-04-argb_1663778107_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/248205/water-cooler-gamer-rise-mode-argb-intel-e-amd-240mm-preto-rm-wcb-04-argb_1663778112_gg.jpg",
    }, {
        "id": 13,
        "nome": "Adaptador P3 X 2 P2 Xcell, Headset, Fone",
        "descricao": "Adaptador P3 X 2 P2, Headset, Fone",
        "garantia": 3,
        "preco": 15,
        "categoria": "perifericos",
        "image_1": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/386780/Adaptador-P2-X-P3-Headset-Fone-Microfone-E-Console-Xc-adp-14-_1713359887_gg.jpg",
    },
    {
        "id": 14,
        "nome": "Suporte Para Headset Sades Wolfbone, Em Acrílico, Azul",
        "descricao": "O WOLFBONE é um suporte lindo e robusto para seu fone de ouvido. A garantia de maior proteção e durabilidade para seu fone. Fácil de montar e compatível com todos os fones. Uma forma prática e com estilo para armazenar seu fone quando não estiver em uso, protegendo de danos, quedas e sujeiras.",
        "garantia": 3,
        "preco": 71.25,
        "categoria": "perifericos",
        "image_1": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/163803/Suporte-Para-Headset-Sades-Wolfbone-Em-Acr-lico-Azul_1667330315_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/163803/Suporte-Para-Headset-Sades-Wolfbone-Em-Acr-lico-Azul_1667330325_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/163803/Suporte-Para-Headset-Sades-Wolfbone-Em-Acr-lico-Azul_1667330336_gg.jpg",
    },
    {
        "id": 15,
        "nome": "Caixa de Som Gamer Rise Mode Aura Sound S4, RGB Rainbow, 3W*2, Preto - RM-SP-04-RGB",
        "descricao": "A Caixa de Som Gamer Rise Mode Aura Sound S4 é a escolha perfeita para quem procura um sistema de som de qualidade para jogos. Com seus alto-falantes de 4W e subwoofer embutido, a Aura Sound S4 oferece um som claro e poderoso, com uma ampla faixa de frequências. Também conta com iluminação RGB personalizável, que vai deixar seu setup ainda mais estiloso.",
        "garantia": 12,
        "preco": 120,
        "categoria": "perifericos",
        "image_1": "https://cdn.awsli.com.br/2500x2500/2597/2597998/produto/2495400170e798535d3.jpg",
        "image_2": "https://cdn.awsli.com.br/600x450/2597/2597998/produto/249540017a8265f1789.jpg",
        "image_3": "https://cdn.awsli.com.br/600x450/2597/2597998/produto/249540017f446b10f5d.jpg",
    },
    {
        "id": 16,
        "nome": "Fone de Ouvido Gamer True Wireless Logitech G FITS USB/Bluetooth, Quatro Microfones, Ajuste LIGHTFORM, PC/Mac, PS, Switch, Preto-985-001205",
        "descricao": "Os fones de ouvido sem fios FITS da Logitech G foram construídos para jogos. Eles têm uma bateria de longa duração e foram desenvolvidos para jogar em PC, Mac, console e celular. Com som nítido e claro com resposta imediata e moldagem LIGHTFORM, que permite que ao adquirir o Logitech G FITS pela primeira vez e em apenas 60 segundos, as pontas se moldem ao ajuste de seus ouvidos, trazendo um novo conceito de conforto ao jogar seus jogos favoritos.",
        "garantia": 24,
        "preco": 1459.99,
        "categoria": "perifericos",
        "image_1": "https://images.kabum.com.br/produtos/fotos/462231/fone-de-ouvido-sem-fio-intra-auricular-gamer-logitech-g-fits-bluetooth-microfones-duplos-preto-985-001205_1685740239_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/462231/fone-de-ouvido-gamer-true-wireless-logitech-g-fits-usb-bluetooth-quatro-microfones-ajuste-lightform-pc-mac-ps-switch-preto-985-001205_1689016192_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/462231/fone-de-ouvido-gamer-true-wireless-logitech-g-fits-usb-bluetooth-quatro-microfones-ajuste-lightform-pc-mac-ps-switch-preto-985-001205_1689016193_gg.jpg",
    },
    {
        "id": 17,
        "nome": "Fone de Ouvido Gamer HyperX Cloud Earbuds II, Com Microfone, Preto - 70N24AA",
        "descricao": "Você não precisa usar um fone de ouvido para levar seus jogos a sério. Se você exige áudio de qualidade e portabilidade conveniente, os HyperX Cloud Earbuds II têm o que você precisa. Com drivers de 14 mm otimizados para áudio móvel, você terá uma ótima experiência auditiva, seja jogando, assistindo vídeos ou ouvindo um bom audiolivro ou podcast. 4 conjuntos de pontas auriculares redesenhadas ajudarão a garantir que você obtenha o ajuste certo para sua orelha.",
        "garantia": 24,
        "preco": 229.99,
        "categoria": "perifericos",
        "image_1": "https://images.kabum.com.br/produtos/fotos/483040/fone-de-ouvido-gamer-hyperx-cloud-earbuds-ii-com-microfone-preto-70n24aa_1701950577_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/483040/fone-de-ouvido-gamer-hyperx-cloud-earbuds-ii-com-microfone-preto-70n24aa_1701950578_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/483040/fone-de-ouvido-gamer-hyperx-cloud-earbuds-ii-com-microfone-preto-70n24aa_1701950581_gg.jpg",
    },
    {
        "id": 18,
        "nome": "Headset Gamer Havit, Drivers 53mm, Microfone Plugável, P2, PC, PS4, XBOX ONE, Preto - HV-H2002D",
        "descricao": "Headset Gamer Havit H2002D. Aparência e textura proporcionais, simples e generosas. Jaqueta de liga leve com frente e superfície de plástico com revestimento de piano. Design Gamer em preto, para combinar com seu setup e além de ter qualidade surpreendente por um preço baixo. Desempenho e Compatibilidade com PC, PS4 e XBOX.",
        "garantia": 12,
        "preco": 175.99,
        "categoria": "perifericos",
        "image_1": "https://images.kabum.com.br/produtos/fotos/102770/headset-gamer-havit-drivers-53mm-hv-h2002d_headset-gamer-havit-drivers-53mm-hv-h2002d_1564056874_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/102770/headset-gamer-havit-drivers-53mm-microfone-plugavel-p2-pc-ps4-xbox-one-preto-hv-h2002d_1709225743_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/102770/headset-gamer-havit-drivers-53mm-microfone-plugavel-p2-pc-ps4-xbox-one-preto-hv-h2002d_1709225744_gg.jpg",
    },
    {
        "id": 19,
        "nome": "Headset Gamer HyperX Cloud Alpha, Drivers 50mm, Múltiplas Plataformas, P2 e P3, Preto e Vermelho - 4P5L1AA#ABL",
        "descricao": "O Headset Gamer HyperX Cloud Alpha é o acessório que você precisava para seus jogos! Este belíssimo headset possui câmaras duplas que atuam perfeitamente no som, separando por completo os sons graves, dos médios e agudos. Isso faz com que as distorções sejam reduzidas e a qualidade boa do som se mantenha por todo o tempo.",
        "garantia": 12,
        "preco": 449.99,
        "categoria": "perifericos",
        "image_1": "https://images.kabum.com.br/produtos/fotos/92357/92357_index_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/92357/92357_1504209648_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/92357/92357_1504209787_gg.jpg",
    },
    {
        "id": 20,
        "nome": "Mouse Gamer Logitech G403 HERO com RGB LIGHTSYNC, 6 Botões Programáveis, Ajuste de Peso e Sensor HERO 25K - 910-005631",
        "descricao": "Projetado para conforto, o G403 possui empunhaduras de borracha em seu redor para controle adicional. O sensor HERO 25K permite rastrear em nível submicrométrico. O LIGHTSYNC RGB de espectro completo e seis botões programáveis colocam você no controle.",
        "garantia": 24,
        "preco": 209.99,
        "categoria": "perifericos",
        "image_1": "https://images.kabum.com.br/produtos/fotos/102649/mouse-gamer-logitech-g403-hero-com-rgb-lightsync-6-botoes-programaveis-ajuste-de-peso-e-sensor-hero-25k-910-005631_1700850718_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/102649/mouse-gamer-logitech-g403-hero-com-rgb-lightsync-6-botoes-programaveis-ajuste-de-peso-e-sensor-hero-25k-910-005631_1669896405_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/102649/mouse-gamer-logitech-g403-hero-com-rgb-lightsync-6-botoes-programaveis-ajuste-de-peso-e-sensor-hero-25k-910-005631_1669896407_gg.jpg",
    }, {
        "id": 21,
        "nome": "Amplificador Frahm Slim 1000 La G5",
        "descricao": "Os amplificadores da linha slim foram desenvolvidos com a mais alta tecnologia em engenharia de áudio. Seus componentes são de alto nível, garantindo reprodução sonora de alta definição. Agora com novo visual e uma parceria exclusiva com mais de 5 playlists frahm pensadas para o seu ambiente! O amplificador slim 1000 la g5 da frahm possui 40 watts rms de potência e é ideal para pequenos ambientes. Possui entradas auxiliar (rca) e de microfone. Diferencial: pode instalar até 12 caixas ou arandelas com 8 ohms cada. Sua instalação é feita de forma simplificada (ligação em paralelo), sem necessidade de conhecimento técnico elevado. Importante: ele aceita qualquer número de caixas ou arandelas inferior a 12 (usa-se de 1 a 12 sem problemas com limite mínimo de impedância). Recomenda-se utilizar com no máximo 35 metros de fio (distância entre a última caixa ou arandela em relação à posição onde ficará o amplificador). Nunca usar transformador tronco ou de linha neste equipamento. Ideal para: projetos com foco em custo/benefício e simplicidade no manuseio. Situações onde outros equipamentos serão usados como fonte de mídia. É indicado também para uso em conjunto com outro amplificador (função line out / line in), solucionando de forma simples e barata a necessidade de volume independente para um ambiente especifico. *imagens meramente ilustrativas.",
        "garantia": 3,
        "peso": 704,
        "preco": 356.99,
        "categoria": "audio",
        "image_1": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/433362/Amplificador-Frahm-Slim-1000-La-G5_1716212633_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/433362/Amplificador-Frahm-Slim-1000-La-G5_1716212644_gg.jpg",
    },
    {
        "id": 22,
        "nome": "Mini System Bluetooth LG CK43",
        "descricao": "O novo Mini System LG CK43 com 220W de potência é a solução ideal para quem busca um mini system compacto para ouvir suas músicas preferidas do smartphone. Além de ter o design inspirado em uma mesa de DJ profissional, ele também possui a função Multi Bluetooth. É possível parear até 3 dispositivos móveis simultaneamente, sem precisar desconectar um smartphone para conectar o outro. Além disso, você pode ver na tela do seu smartphone as músicas enviadas pelos três aparelhos, podendo escolher a música a ser reproduzida e até mesmo alterar a ordem com a função Multi Playlist. Com o aplicativo LG Music Flow Bluetooth é possível controlar todas as funções do aparelho em 3 smartphones ao mesmo tempo. Você também pode assistir seus programas favoritos, como séries e filmes, com máxima potência, conectando sem fios seu mini system ao seu televisor LG através da função Sound Sync Wireless. Em resumo, o Mini System LG CK43 é uma excelente opção para quem busca qualidade de som e praticidade na hora de ouvir suas músicas preferidas. Com sua potência de 220W, design inspirado em mesa de DJ profissional, função Multi Bluetooth e possibilidade de conexão com outros dispositivos LG, ele oferece uma experiência completa de áudio e entretenimento.",
        "garantia": 12,
        "peso": 7400,
        "preco": 1099.99,
        "categoria": "audio",
        "image_1": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/549557/Mini-System-Lg-Xboom-Ck43n-Preto-220w-Rms-Bluetooth-Fm-Bivolt_1713972021_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/549557/Mini-System-Lg-Xboom-Ck43n-Preto-220w-Rms-Bluetooth-Fm-Bivolt_1713972032_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/549557/Mini-System-Lg-Xboom-Ck43n-Preto-220w-Rms-Bluetooth-Fm-Bivolt_1713972054_gg.jpg",
    },
    {
        "id": 23,
        "nome": "Mini System Sony 95430 HCD-GT3D M LA9",
        "descricao": "O mini system HCD-GT3D da Sony com som surround combina home theater com festa em casa, de uma noite de cinema a uma festa, enquanto as luzes de DJ embutidas no alto-falante criam a atmosfera perfeita. Um subwoofer de 20 cm (7,9”) incorpora o impacto dos graves em cada explosão e ressonância da linha de graves. Melhore os graves com o MEGA BASS. Desfrute de uma verdadeira atmosfera de festa graças à exibição de luzes vivas do alto-falante de subwoofer LED. As luzes multicoloridas são projetadas no chão, teto ou parede, e você pode escolher padrões de linhas e pontos. Com conectividade Bluetooth e NFC, você pode transmitir suas músicas favoritas de um smartphone. Reproduz CDs e dispositivos USB.",
        "garantia": 12,
        "peso": 20622,
        "preco": 1200,
        "categoria": "audio",
        "image_1": "https://images.kabum.com.br/produtos/fotos/352681/mini-system-sony-95430-hcd-gt3d-m-la9-led-blutooth-720w-preto_1654113139_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/352681/mini-system-sony-95430-hcd-gt3d-m-la9-led-blutooth-720w-preto_1654113138_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/352681/mini-system-sony-95430-hcd-gt3d-m-la9-led-blutooth-720w-preto_1654113140_gg.jpg",
    },
    {
        "id": 24,
        "nome": "Controladora Hercules DJControl Inpulse 200",
        "descricao": "A Hercules introduz a primeira gama de sempre de controladores de DJing para aprender realmente a misturar. Treine o seu ouvido e aprenda a dominar o beatmatching manualmente com o DJControl Inpulse 200. O seu design fácil de utilizar e o conforto fazem dele o controlador perfeito para começar com o DJing. Controlado pelo software DJUCED, o DJControl Inpulse 200 oferece novas funcionalidades para o ajudar a aprender: guias luminosos no controlador para aprender os movimentos certos, o Intelligent Music Assistant (IMA) para o ajudar a escolher as melhores músicas para tocar, a funcionalidade ENERGY para gerir o ambiente da festa e a DJ Academy com os seus tutoriais em vídeo integrados. Tem tudo o que precisa para se tornar um DJ.",
        "garantia": 12,
        "peso": 1490,
        "preco": 949.99,
        "categoria": "audio",
        "image_1": "https://images.kabum.com.br/produtos/fotos/450242/controladora-hercules-djcontrol-inpulse-200-mk2-4-pads-preto-4780940_1687282224_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/450242/controladora-hercules-djcontrol-inpulse-200-mk2-4-pads-preto-4780940_1687282226_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/450242/controladora-hercules-djcontrol-inpulse-200-mk2-4-pads-preto-4780940_1687282225_gg.jpg",
    },
    {
        "id": 25,
        "nome": "Kit Microfone Áudio Technica At2020, USB Pack + Fone M20x E Suporte Articulado",
        "descricao": "O Kit AT2020USB+PK foi projetado para streamers, podcasters e outros criadores de conteúdo que precisam de uma instalação de microfone versátil, fácil de instalar e fácil de ajustar. O Kit inclui um microfone USB condensador cardióide AT2020USB+, um fone de ouvido profissional ATH-M20x e um suporte ajustável de mesa com um cabo USB. O suporte ajustável prende-se com segurança a mesa e outras superfícies planas de até 55 mm (2,2 \") de espessura. A lança é rosqueada internamente com um cabo USB para uma aparência limpa e operação sem obstáculos. Oferecendo rotação completa de 360° e ajustável, articulações estabilizadas por mola, o braço da lança é reposicionado rapidamente para o posicionamento ideal do microfone. Oferecendo o som aclamado pela crítica do AT2020 com uma saída USB, o microfone AT2020USB+ é ideal para podcasting, streaming, gravação em estúdio doméstico e uso de narração. O microfone possui um fone de ouvido embutido com controle de volume que permite monitorar diretamente o sinal do microfone sem demora. Ele também oferece um controle de mixagem que combina microfone e áudio pré-gravado. O padrão de captação cardióide do microfone oferece excelente rejeição fora do eixo, enquanto seu conversor AD com uma taxa de amostragem de 44,1 bits / 44,1 kHz de 16 bits garante uma reprodução de som extremamente articulada.",
        "garantia": 12,
        "peso": 576,
        "preco": 2184.99,
        "categoria": "audio",
        "image_1": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/406571/Kit-Microfone-udio-Technica-At2020-USB-Pack-Fone-M20x-E-Suporte-Articulado_1692886691_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/406571/Kit-Microfone-udio-Technica-At2020-USB-Pack-Fone-M20x-E-Suporte-Articulado_1692886702_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/406571/Kit-Microfone-udio-Technica-At2020-USB-Pack-Fone-M20x-E-Suporte-Articulado_1692886714_gg.jpg",
    },
    {
        "id": 26,
        "nome": "Kit Dvr Gravador De Vídeo, FULL HDx 3316, 16 Canais, Com Detecção De Movimento + Hd 500GB",
        "descricao": "Kit dvr gravador de vídeo tudo forte tfhdx 3316 16 canais com detecção de movimento + hd 500gb nós da tudo forte, criamos este kit para facilitar sua compra, e você não se preocupar com mais nada. A tranquilidade que faltava no seu dia-a-dia, dentro ou fora de casa ou do seu negócio. itens inclusos no kit 01 dvr gravador de vídeo tudo forte tfhdx 3316 16 canais 01 hd para memória de gravação de 500gb características tfhdx 3316: compatíveis com as tecnologias hdcvi, ahd, hdtvi, analógico (cvbs) e ip alta resolução de imagem 1080p compressão de vídeo h.265 detecção de movimento monitoramento via aplicativo xmeye monitore de onde estiver acesse as imagens do gravador através do seu tablet ou smartphone de maneira rápida e prática.",
        "garantia": 12,
        "peso": 1900,
        "preco": 10,
        "categoria": "audio",
        "image_1": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/551560/Kit-Dvr-Gravador-De-V-deo-FULL-HDx-3316-16-Canais-Com-Detec-o-De-Movimento-Hd-500GB_1713452272_gg.jpg",
        "image_2": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/551560/Kit-Dvr-Gravador-De-V-deo-FULL-HDx-3316-16-Canais-Com-Detec-o-De-Movimento-Hd-500GB_1713452333_gg.jpg",
        "image_3": "https://images.kabum.com.br/produtos/fotos/sync_mirakl/551560/Kit-Dvr-Gravador-De-V-deo-FULL-HDx-3316-16-Canais-Com-Detec-o-De-Movimento-Hd-500GB_1713452372_gg.jpg",
    },
]